---
title: "Data tidyup"
output: html_document
date: "2024-03-24"
runtime: shiny
---
```{r}
library(dplyr)

```


```{r}
#!/usr/bin/env Rscript
token <- "C6A6C5258029ABACFDA0CEB02C208A86"
url <- "https://redcap.wehi.edu.au/api/"
formData <- list("token"=token,
    content='record',
    action='export',
    format='csv',
    type='flat',
    csvDelimiter='',
    rawOrLabel='raw',
    rawOrLabelHeaders='raw',
    exportCheckboxLabel='false',
    exportSurveyFields='false',
    exportDataAccessGroups='false',
    returnFormat='csv'
)
response <- httr::POST(url, body = formData, encode = "form")
result <- httr::content(response)
print(result)
```


```{r}
data <- result

# Fill NA values in 'redcap_repeat_instrument' column with "patient"
data$redcap_repeat_instrument <- ifelse(is.na(data$redcap_repeat_instrument), "patient", data$redcap_repeat_instrument)

# Split the dataframe into a list of dataframes based on the values in 'redcap_repeat_instrument'
df_list <- split(data, data$redcap_repeat_instrument)

# If you want to assign each dataframe to a separate variable, you can do:
df_patient <- df_list[["patient"]]
df_condition <- df_list[["conditions"]]
df_medication <- df_list[["medications"]]
```


```{r}
df_patient
```

```{r}
#choose a condition
observe_condition <- "Ischemic heart disease (disorder)"

#filter out condition that matches
df_condition <- filter(df_condition, description_condition == observe_condition)

#keep only the patient records that show in df_condition
df_patient <- semi_join(df_patient, df_condition, by = "id_patient")

#keep only the medicine that has matched encounter in condition
df_medication <- semi_join(df_medication, df_condition, by = c("encounter_medication" = "encounter_condition"))



```


```{r}
print(df_condition$description_condition)
```

create a data frame for Geo map.
```{r}
#filter out the required column for geo map
geo_column <- c("Id","ZIP","RACE","GENDER","ETHNICITY","INCOME","HEALTHCARE_EXPENSES","HEALTHCARE_COVERAGE","CONDITION","OBSERVED_CONDITION","VALUE","Suburb")

geo_patient_selected <- df_patient %>%
  select(Id = id_patient, ZIP = zip_patient, RACE = race_patient, GENDER = gender_patient, ETHNICITY = ethnicity_patient, INCOME = income_patient, HEALTHCARE_EXPENSES = healthcare_expenses_patient, HEALTHCARE_COVERAGE = healthcare_coverage_patient, Suburb = county_patient) %>%
  mutate(ZIP = as.integer(ZIP))

geo_condition_selected <- df_condition %>%
  select(CONDITION = description_condition) 

geo_data <- cross_join(geo_patient_selected, geo_condition_selected)

geo_data

```







```{r}
chosen_column <- c("id_patient", "redcap_repeat_instrument", "redcap_repeat_instance", "birthdate_patient", "deathdate_patient", "ethnicity_patient", "gender_patient", "county_patient", "healthcare_expenses_patient", "income_patient", "start_medication", "encounter_medication", "description_medication", "start_condition", "encounter_condition", "description_condition")

data <- result %>%
  select(!!!chosen_column)

```

```{r}
print(data)
```


